#!/usr/bin/env node
// Runs one Codex turn through `codex app-server` (JSON-RPC over stdio) at a declared rights level.
//
// Why app-server rather than `codex exec`: exec forces approval_policy=Never internally. Where an MDM
// profile restricts the allowed policies, Never is clamped to untrusted and every read, command and
// write is then rejected — while the process still exits 0. app-server takes a per-thread approvalPolicy,
// and "on-request" is normally permitted.
//
// Protocol facts are pinned in ./schema-<version>/ (generated by `codex app-server generate-json-schema`).
// Three of them are load-bearing and were each got wrong before:
//   * There is no `turn/failed` method. Failure arrives as turn/completed with params.turn.status in
//     {completed, interrupted, failed, inProgress}. Arrival is not success.
//   * Codex spawns its own subagents on other threads. Every event must be filtered by the root
//     threadId, or a child's command satisfies the gate, a child's message becomes the answer, and a
//     child's turn/completed tears down the session while the root turn is still running.
//   * Server-to-client requests are not all approvals. Attestation, ChatGPT token refresh and MCP
//     elicitation share the same channel and take different responses.
//
// Escalation policy: an escalation request means the sandbox was sized wrong for the task, so it is
// surfaced loudly rather than silently waved through or silently refused. Widen the sandbox with
// --writable / --network instead of trying to approve your way out of it.

import { spawn, spawnSync } from "node:child_process";
import readline from "node:readline";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const EXIT = { OK: 0, TURN_NOT_COMPLETED: 1, USAGE: 2, TIMEOUT: 3, TRANSPORT: 4, NO_COMMANDS: 5, ESCALATED: 6, INTERACTION: 7, NO_ANSWER: 8, VERIFY_FAILED: 9, BUSY: 10, COMMAND_FAILED: 11, VERIFY_UNMEASURABLE: 12 };
const LEVELS = new Set(["read", "write"]);
const READ_PROFILE = "codex_delegate_read";
// The full ladder the model catalogue advertises (`codex debug models` -> supported_reasoning_levels),
// not a subset: rejecting `max` as a usage error while the user's own config.toml asked for it is the
// driver overruling the caller about the one thing it has no opinion on.
const EFFORTS = new Set(["low", "medium", "high", "xhigh", "max", "ultra"]);
const MAX_PROMPT_BYTES = 512 * 1024;
// --timeout is the caller's whole budget, so anything the driver spends after the turn — the verifier —
// has to come out of what is left of it rather than out of a private allowance.
const startedAtMs = Date.now();

function fail(code, msg) {
  process.stderr.write(`codex-delegate: ${msg}\n`);
  process.exitCode = code;
  // A refusal always ends the run, so mark it settled: shutdown() SIGTERMs the child, and the child's exit
  // handler would otherwise rewrite this code to TRANSPORT. That made every post-spawn refusal report 4,
  // including the documented exit 10 for resuming a thread whose turn is still open — a coordinator that
  // backs off on 10 and escalates on 4 did the wrong thing on the one contended case the skill publishes.
  settled = true;
  throw new Bail();
}
class Bail extends Error {}

// ---------------------------------------------------------------- arguments

const USAGE = `codex-delegate — run one Codex turn with rights declared per call.

  node driver.mjs --level read|write --cwd DIR [options] --prompt TEXT
  node driver.mjs --level read --cwd DIR < task.txt

Rights
  --level read       read anything, write only $TMPDIR; no lock is taken, so read
                     seats run in parallel over one directory
  --level write      workspace-write over --cwd; takes a per-directory lock
  --writable DIR     grant one more root (write level only, repeatable)
  --network          allow egress (write level only)
  --commit           also grant the git common dir, for a turn that commits

Turn
  --prompt TEXT      the task; omit to read it from stdin
  --model NAME       omit to use whatever config.toml chose
  --effort ${[...EFFORTS].join("|")}
  --timeout SECONDS  default 900, at most 7200
  --resume THREAD    continue a thread; --ephemeral leaves no thread behind

Gate — what counts as the turn having done the work
  --expect-command RE   a command matching RE must have run
  --verify CMD          run CMD after the turn; its exit code decides
  --allow-no-commands   accept a turn that ran nothing

Isolation
  by default the turn runs against a private CODEX_HOME, so the caller's own
  plugins, skills and memories cannot steer it and it writes no trust records
  back; auth.json and sessions stay linked to the real home
  --host-home        use the caller's ~/.codex instead, plugins and all

Report
  --json             machine-readable on stdout; otherwise a human footer

Exit codes, in the order they are decided
  0 ok        2 usage      4 transport   10 busy (another run holds the lock)
  3 timeout   1 turn not completed       7 wanted input   6 escalated
  12 verify unmeasurable  9 verify failed   5 no commands  8 no answer
  11 a command failed
`;

function parseArgs(argv) {
  // No effort default. Sending one unconditionally silently downgraded whatever config.toml asked for —
  // measured: a user whose config said `max` got `low` on every delegation. --model already works this
  // way (null means "whatever the config chose"); effort now matches it.
  const o = { level: "read", timeout: 900, writable: [] };
  const need = (i, flag) => {
    const v = argv[i];
    if (v === undefined || v === "" || v.startsWith("--")) fail(EXIT.USAGE, `${flag} requires a non-empty value`);
    return v;
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    switch (a) {
      case "--level": o.level = need(++i, a); break;
      case "--cwd": o.cwd = need(++i, a); break;
      case "--effort": o.effort = need(++i, a); break;
      case "--model": o.model = need(++i, a); break;
      case "--timeout": o.timeout = Number(need(++i, a)); break;
      case "--prompt": o.prompt = argv[++i] ?? fail(EXIT.USAGE, "--prompt requires a value"); break;
      case "--writable": o.writable.push(need(++i, a)); break;
      case "--commit": o.commit = true; break;
      case "--resume": o.resume = need(++i, a); break;
      case "--ephemeral": o.ephemeral = true; break;
      case "--allow-no-commands": o.allowNoCommands = true; break;
      case "--expect-command": o.expect = need(++i, a); break;
      case "--verify": o.verify = need(++i, a); break;
      case "--network": o.network = true; break;
      case "--host-home": o.hostHome = true; break;
      case "--json": o.json = true; break;
      // Asking for help is not a usage error: it goes to stdout and exits 0, so `--help | head` works.
      case "-h": case "--help": process.stdout.write(USAGE); process.exit(EXIT.OK); break;
      default: fail(EXIT.USAGE, `unknown argument: ${a}`);
    }
  }
  if (!LEVELS.has(o.level)) fail(EXIT.USAGE, `--level must be one of ${[...LEVELS].join("|")}`);
  if (o.effort !== undefined && !EFFORTS.has(o.effort))
    fail(EXIT.USAGE, `--effort must be one of ${[...EFFORTS].join("|")}`);
  if (!Number.isFinite(o.timeout) || o.timeout <= 0 || o.timeout > 7200)
    fail(EXIT.USAGE, "--timeout must be a positive number of seconds, at most 7200");
  if (!o.cwd) fail(EXIT.USAGE, "--cwd is required");
  if (o.commit && o.level !== "write") fail(EXIT.USAGE, "--commit requires --level write");
  if (o.ephemeral && o.resume) fail(EXIT.USAGE, "--ephemeral and --resume are contradictory");
  // Compile it now: an invalid pattern thrown from inside the report handler kills the run long after
  // the work is done, and costs the whole delegation.
  if (o.expect !== undefined) {
    try { o.expectRe = new RegExp(o.expect); }
    catch (e) { fail(EXIT.USAGE, `--expect-command is not a valid regular expression: ${e.message}`); }
  }
  return o;
}

function resolveDir(p, what) {
  let real;
  try { real = fs.realpathSync(path.resolve(p)); } catch { fail(EXIT.USAGE, `${what} does not exist: ${p}`); }
  if (!fs.statSync(real).isDirectory()) fail(EXIT.USAGE, `${what} is not a directory: ${real}`);
  return real;
}

// A writable root of / or $HOME is never what the caller meant; refuse rather than hand it over.
//
// Compared by IDENTITY, walking up from home, because a string comparison is bypassable and was: macOS
// realpath does not normalise letter case, so `fs.realpathSync("/users/ruliny")` returns it unchanged and
// `"/users/ruliny" !== "/Users/ruliny"` let a --level write run take the whole home directory. Measured:
// the correct spelling exited 2, the case variant exited 0 and ran. dev:ino collapses case, symlinks and
// every other spelling of the same directory at once — the same fix the cwd lock already uses.
function checkRoot(dir) {
  let target;
  try { target = fs.statSync(dir); }
  catch (e) { fail(EXIT.USAGE, `cannot stat ${dir}: ${e.message}`); }
  const same = (st) => st.dev === target.dev && st.ino === target.ino;
  // Refusing home exactly is not enough: any ANCESTOR of it grants it too, and so does the filesystem
  // root. Walk home upward and refuse if the candidate is any of them.
  // Anchored on the PASSWD entry, not on $HOME. Fixing the comparison to use dev:ino left the anchor
  // mutable, which is the same bug one level up: with HOME unset or pointed at a decoy, `--cwd $HOME` at
  // write level exited 0 and the turn got the whole home directory. os.userInfo().homedir reads passwd and
  // ignores the environment; a deliberate HOME is still honoured by walking it too, so setting HOME can
  // only ever ADD a refusal, never remove one.
  const canon = (a) => { try { return fs.realpathSync(path.resolve(a)); } catch { return path.resolve(a); } };
  const hit = (p, why) => {
    let st = null;
    try { st = fs.statSync(p); } catch {}
    if (st && same(st)) fail(EXIT.USAGE, `refusing to grant write access to ${dir}: it is ${why}`);
  };
  // The passwd home and everything ABOVE it: granting an ancestor grants the home too.
  for (let cur = canon(passwdHome("the home-directory guard")); ; ) {
    hit(cur, cur === canon(passwdHome("the home-directory guard")) ? "your home directory" : `an ancestor of your home directory (${cur})`);
    const parent = path.dirname(cur);
    if (parent === cur) break;
    cur = parent;
  }
  // A deliberate $HOME is honoured, but ONLY as an exact match and only when absolute. Walking its
  // ancestors refused legitimate layouts: a hermetic build with HOME=$W/.home could not use $W as its
  // workspace at all. And a RELATIVE HOME resolves against the driver's own cwd, which would promote an
  // arbitrary directory to a home anchor. The security argument rests on the passwd entry above; this is
  // only politeness toward someone who moved HOME on purpose.
  const envHome = process.env.HOME;
  if (envHome && path.isAbsolute(envHome)) hit(canon(envHome), `the directory $HOME points at (${envHome})`);
  return dir;
}

// A write-capable run owns its cwd for the duration. Two concurrent runs in one directory edit, test and
// clean up over each other, and each can validate the other's half-finished state. Documentation asking
// callers to use unique directories is advice; this is enforcement.
//
// The lock does NOT live in the directory it protects. At --level write with --commit, a turn running
// `git add -A` stages and commits it, and releaseLock then leaves the worktree dirty with a deleted file.
// $TMPDIR is no home for it either, for two measured reasons: it is a mutable env var, so two runs on one
// cwd under different TMPDIRs take two different locks and both proceed — mutual exclusion silently lost —
// and the --level read profile grants Codex write access to exactly that directory.
// os.homedir() falls back to the passwd entry when HOME is unset, and no rights level can write there.
// os.userInfo() rather than os.homedir(), which PREFERS $HOME: two runs on one cwd under different HOME
// values took two different locks and both proceeded — measured, with the lock files sitting in two homes.
// With HOME="" it is worse: os.homedir() returns "", LOCK_DIR becomes RELATIVE, and the lock is created
// inside the invocation directory — exactly the `git add -A` hazard the comment above exists to avoid.
// Resolved LAZILY, and never at module scope. os.homedir() never consulted passwd; os.userInfo() always
// does and THROWS for a uid with no passwd entry — a container run with --user 1000000, an OpenShift
// random uid. At module top level that ran before parseArgs and outside main()'s try, so it produced a raw
// V8 stack trace and exit 1 — which on the published ladder means "the turn did not complete", telling a
// coordinator the turn ran when codex was never spawned.
function passwdHome(what) {
  try { return os.userInfo().homedir; }
  catch (e) { fail(EXIT.USAGE, `cannot resolve your home directory from the passwd database, which ${what} needs (${e.code ?? e.message}); this happens for a uid with no passwd entry`); }
}
const lockDir = () => path.join(passwdHome("the cwd lock"), ".codex-delegate", "locks");

// Codex reads its plugins, skills, memories and project-trust records out of CODEX_HOME, so delegating
// into the caller's own home makes every turn a function of whatever they happen to have installed.
// Measured over the 157 delegations this machine had already run: 95 of them spent their FIRST tool call
// reading ~/.codex/plugins/cache rather than the task, 209 of 919 tool calls went there, and one turn
// ended having done nothing but announce that it had to run a plugin's workflow first. A private home
// removes that input entirely — and, as a side effect, stops each run appending a trusted-project record
// to the caller's config.toml, which is how that file reached 36 KB of dead temp directories.
//
// Two things are linked back rather than isolated. auth.json, so a token refresh still lands in the real
// file instead of expiring inside a cache directory. sessions, because the rollout it holds is the only
// evidence OUTSIDE this process that the turn ran at all: a caller who cannot find the rollout cannot tell
// a seat that did the work from a wrapper that reported success without doing any.
//
// Anchored on passwd for the same reason the lock is: $HOME is attacker- and accident-mutable, and two
// runs under two HOME values would silently use two different homes.
function isolatedHome() {
  const base = passwdHome("the isolated Codex home");
  const home = path.join(base, ".codex-delegate", "home");
  try { fs.mkdirSync(home, { recursive: true, mode: 0o700 }); }
  catch (e) { fail(EXIT.USAGE, `cannot create the isolated Codex home ${home}: ${e.message}`); }
  for (const name of ["auth.json", "sessions"]) {
    const link = path.join(home, name), target = path.join(base, ".codex", name);
    if (!fs.existsSync(target)) continue;   // nothing to share yet; codex creates its own
    let current = null;
    try { current = fs.readlinkSync(link); } catch (e) {
      // Anything that is not a symlink is a real file someone put there, possibly holding real state.
      // Replacing it silently is how a token or a session archive disappears, so stop and say which.
      if (e.code !== "ENOENT")
        fail(EXIT.USAGE, `${link} exists but is not a symbolic link; move it aside or pass --host-home`);
    }
    if (current === target) continue;
    try {
      if (current !== null) fs.unlinkSync(link);
      fs.symlinkSync(target, link);
    } catch (e) { fail(EXIT.USAGE, `cannot link ${link} -> ${target}: ${e.message}`); }
  }
  return home;
}
// A retry is consumed only by reclaiming a stale lock or by the lock vanishing under us, and each needs a
// distinct peer state transition — so the bound covers the plausible fan-out width, not a spin. Measured
// contention (100 concurrent pairs) needed zero retries, so this is headroom, not a working budget.
const LOCK_ATTEMPTS = 10, LOCK_RETRY_MS = 20;
const sleepSync = (ms) => { Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms); };

// Classify whatever is at the lock path without trusting it. O_NOFOLLOW keeps a symlink from redirecting
// us, O_NONBLOCK keeps a FIFO from blocking the open forever (measured: a fifo there hung a run past its
// own --timeout, which cannot fire because acquireLock runs before the deadline is armed), and fstat
// catches a directory before readFileSync throws EISDIR — which used to escape as exit 4, claiming codex
// had crashed before codex was even spawned.
//
// Returns {gone:true} when the lock vanished under us, else {held} where held is the parsed contents or
// null if they would not parse. Those two are NOT the same state and must not share a return value: a
// vanished lock means retry, an unparsable one means reclaim, and collapsing them turns a crashed peer's
// empty lock into a permanently contended directory.
function inspectLock(p, dir) {
  let fd;
  try { fd = fs.openSync(p, fs.constants.O_RDONLY | fs.constants.O_NONBLOCK | fs.constants.O_NOFOLLOW); }
  catch (e) {
    if (e.code === "ENOENT") return { gone: true };
    if (e.code === "ELOOP") fail(EXIT.USAGE, `cannot lock ${dir}: ${p} is a symbolic link, not a lock file; remove it and retry`);
    fail(EXIT.USAGE, `cannot lock ${dir}: ${p} exists but cannot be read (${e.code}); remove it or fix its permissions`);
  }
  try {
    const st = fs.fstatSync(fd);
    if (!st.isFile()) {
      const kind = st.isDirectory() ? "a directory" : st.isFIFO() ? "a named pipe" : st.isSocket() ? "a socket" : "not a regular file";
      fail(EXIT.USAGE, `cannot lock ${dir}: ${p} is ${kind}, not a lock file; remove it and retry`);
    }
    let held = null;
    try { held = JSON.parse(fs.readFileSync(fd, "utf8")); } catch {}
    return { held };
  } finally { fs.closeSync(fd); }
}

// Is the pid in a lock file a process that still exists? EPERM means it exists and belongs to another
// user; only ESRCH proves it is gone. An unparsable lock names no pid and cannot be honoured.
function holderAlive(held) {
  const holder = Number(held?.pid);
  if (!Number.isInteger(holder) || holder <= 0) return false;
  try { process.kill(holder, 0); return true; } catch (e) { return e.code === "EPERM"; }
}

// Removes the lock at `p` if and only if it is still stale, with at most one process doing so at a time.
// Returns false when another process holds the reclaim marker, meaning "retry the whole acquisition".
//
// Abandonment is decided by the marker OWNER'S LIVENESS, never by a clock. An mtime deadline was both too
// eager and too slow: it stole the marker from a live owner that had merely been stalled past the deadline
// — a laptop sleep, a SIGSTOP, a wall-clock step — which reopens the multi-holder window the marker exists
// to close; and it wedged a provably FREE directory for the whole deadline whenever a run was killed
// mid-reclaim, measured as exit 10 "contended" on a lock whose owner did not exist. A stalled process is
// alive, so nobody steals its marker and the worst case is an honest BUSY; a dead owner's marker is
// abandonable immediately. The mtime bound survives only as a backstop against a recycled marker pid.
const RECLAIM_BACKSTOP_MS = 3600000;
function reclaimStale(p, dir) {
  const rp = `${p}.reclaim`;
  const tmp = `${p}.${process.pid}.rtmp`;
  try {
    fs.writeFileSync(tmp, String(process.pid));
    try { fs.linkSync(tmp, rp); }
    catch (e) {
      if (e.code !== "EEXIST") fail(EXIT.USAGE, `cannot reclaim the stale lock ${p}: ${e.message}`);
      // Someone is reclaiming right now — unless the process named in their marker is gone.
      try {
        const owner = Number(fs.readFileSync(rp, "utf8").trim());
        const abandoned = !holderAlive({ pid: owner }) || Date.now() - fs.statSync(rp).mtimeMs > RECLAIM_BACKSTOP_MS;
        if (abandoned) fs.rmSync(rp, { force: true });
      } catch {}
      return false;
    }
  } finally { fs.rmSync(tmp, { force: true }); }
  try {
    // Ask again, under the reclaim lock. The lock may have been reclaimed by someone else and retaken by
    // a live process since we last looked; deleting it then is exactly the bug this exists to prevent.
    const now = inspectLock(p, dir);
    if (!now.gone && !holderAlive(now.held)) fs.rmSync(p, { force: true });
  } finally { fs.rmSync(rp, { force: true }); }
  return true;
}

let lockPath = null;
function acquireLock(dir) {
  // Keyed on the directory's IDENTITY, not on how it was spelled. realpath normalises symlinks but not
  // letter case, so on a case-insensitive volume `--cwd .../Worktree` and `--cwd .../worktree` are one
  // directory with two hashes — measured, and the second run walked straight in. dev:ino covers case,
  // renames and every other aliasing at once. The body still records the path, for the human who finds it.
  let st;
  try { st = fs.statSync(dir); }
  catch (e) { fail(EXIT.USAGE, `cannot stat --cwd ${dir}: ${e.message}`); }
  const LOCK_DIR = lockDir();
  const p = path.join(LOCK_DIR, `${crypto.createHash("sha256").update(`${st.dev}:${st.ino}`).digest("hex")}.lock`);
  try { fs.mkdirSync(LOCK_DIR, { recursive: true, mode: 0o700 }); }
  catch (e) { fail(EXIT.USAGE, `cannot create the lock directory ${LOCK_DIR}: ${e.message}`); }
  // The file name is a hash, so the contents have to say what it locks — for the message below and for a
  // human who finds a stale one.
  const body = JSON.stringify({ pid: process.pid, cwd: dir, started: new Date().toISOString() });
  // Creation is ATOMIC, not merely exclusive. `writeFileSync(..., "wx")` creates the file and then writes
  // it, so there is a window in which the lock exists but is empty — and an empty lock reads as abandoned,
  // which is the one thing a lock must never do. Writing to a private temp file and link(2)-ing it into
  // place means it is fully formed the instant it becomes visible; link fails EEXIST if someone got there
  // first. Reverting this alone did NOT reproduce a violation in 19 acquisitions, so it is not the fix for
  // the race below — it is here because the window is real and the cost of losing it is two writers in one
  // repository, not because a measurement forced it.
  const tmp = `${p}.${process.pid}.tmp`;
  for (let attempt = 0; attempt < LOCK_ATTEMPTS; attempt++) {
    let linked = false;
    try {
      fs.writeFileSync(tmp, body);
      fs.linkSync(tmp, p);
      linked = true;
    } catch (e) {
      if (e.code !== "EEXIST") fail(EXIT.USAGE, `cannot lock ${dir} (${p}): ${e.message}`);
    } finally {
      fs.rmSync(tmp, { force: true });
    }
    if (linked) { lockPath = p; return; }
    {
      const seen = inspectLock(p, dir);
      // Vanished between our failed create and the read: a peer released it. Retry, do not report a
      // transport failure — that used to surface as exit 4 on an ordinary release.
      if (seen.gone) { sleepSync(LOCK_RETRY_MS); continue; }
      // An unparsable lock names no live pid, so it cannot be honoured. Since creation is atomic this is
      // no longer a half-written file from a peer — it is a hand-made or corrupted one — but treating it
      // as held would wedge the directory forever, so it is reclaimed like any other stale lock.
      const held = seen.held;
      const holder = Number(held?.pid);
      if (holderAlive(held)) fail(EXIT.BUSY,
        `${dir} is in use by codex-delegate pid ${holder} (started ${held?.started ?? "unknown"}); ` +
        `give each concurrent run its own cwd. If that process is gone, delete ${p}`);
      // Reclaiming a stale lock is where mutual exclusion actually broke, and neither an unlink nor a
      // rename fixes it: both act on the PATH, not on the file that was inspected. A peer that judged the
      // STALE lock dead arrives late and removes the FRESH, live lock that has since replaced it, then
      // takes the directory. Measured by logging the acquire/release interval of every process in an
      // eight-way fan-out over a planted stale lock: the old unconditional unlink produced 6 violations
      // and up to THREE simultaneous holders; serialising the reclaim gives 0 and a maximum of 1.
      //
      // (Counting how many runs exited 0 does not measure this and will mislead you: runs that acquire in
      // sequence all succeed, correctly. Only overlapping hold intervals are evidence.)
      //
      // The reclaim is serialised by its own short-lived lock, and the liveness question is asked again
      // UNDER it. Only one process can be deleting the lock at a time, and it deletes only what it has
      // just re-confirmed to be dead — so a lock created in the meantime is seen as live and survives.
      if (!reclaimStale(p, dir)) { sleepSync(LOCK_RETRY_MS); continue; }
    }
  }
  fail(EXIT.BUSY, `${dir} is contended: the lock at ${p} changed hands ${LOCK_ATTEMPTS} times without settling`);
}
function releaseLock() {
  if (!lockPath) return;
  try { if (JSON.parse(fs.readFileSync(lockPath, "utf8")).pid === process.pid) fs.rmSync(lockPath, { force: true }); } catch {}
  lockPath = null;
}

// The read level's whole safety argument is "$TMPDIR is writable and nothing else is", so that is what
// gets checked — the EFFECT the server reports, not the NAME of the profile that was supposed to produce
// it. Checking the name is not enough, measured: misspell a field inside permissions.<id> and the grant
// silently vanishes (sandbox flips to {"type":"readOnly"}, writableRoots disappears) while
// activePermissionProfile still reads back the correct id. --strict-config does not catch that typo
// either, so a name-only assert passes while the thing it guards is gone.
//
// Paths are canonicalised on BOTH sides rather than string-compared: the server resolves intermediate
// symlinks (/var/... -> /private/var/...) but leaves a symlinked FINAL component alone, so no single
// string transform matches every shape TMPDIR can take.
function canonPath(p) {
  try { return fs.realpathSync(path.resolve(p)); } catch { return null; }
}
// Both levels are checked, because guarding only the read one was an asymmetry rather than a decision:
// read was the level with something clever to verify, so it got the attention, while WRITE — the level
// that can actually damage a repository — accepted whatever cwd, network setting and writable-root set the
// server chose to report. What each level expects differs, but "assert the effect the server reports"
// does not.
function assertSandbox(thread) {
  return opts.level === "read" ? assertReadSandbox(thread) : assertWriteSandbox(thread);
}

// At write level the server reports the grant differently, measured against the live binary: the cwd is
// NOT in writableRoots — it is implied by workspaceWrite and appears in runtimeWorkspaceRoots — so
// writableRoots holds exactly the EXTRA roots from --writable/--commit and is empty without them. The
// permission profile is null here, because sending `sandbox` at all suppresses it.
function assertWriteSandbox(thread) {
  const refuse = (why) => fail(EXIT.TRANSPORT,
    `the write sandbox is not what was asked for (${why}); refusing to continue rather than run under an unknown sandbox`);
  const sb = thread.sandbox ?? null;
  if (sb?.type !== "workspaceWrite") refuse(`sandbox type is ${JSON.stringify(sb?.type ?? null)}`);
  // Egress is opt-in and the flag is the whole of the opt-in; a server granting it unasked is a widening.
  if (Boolean(sb.networkAccess) !== Boolean(opts.network))
    refuse(`networkAccess is ${Boolean(sb.networkAccess)} but --network was ${opts.network ? "given" : "not given"}`);
  const want = [...roots].map(canonPath).sort();
  const got = (sb.writableRoots ?? []).map(canonPath).sort();
  if (want.length !== got.length || want.some((r, i) => r !== got[i]))
    refuse(`writable roots are ${JSON.stringify(sb.writableRoots ?? [])}, expected ${JSON.stringify(roots)}`);
  // The cwd is the primary grant and the one the caller reasoned about; if the server put a different
  // directory there, everything the turn writes lands somewhere the caller did not choose.
  const workspace = (thread.runtimeWorkspaceRoots ?? []).map(canonPath);
  if (!workspace.includes(canonPath(cwd)))
    refuse(`the workspace roots are ${JSON.stringify(thread.runtimeWorkspaceRoots ?? [])}, which do not include --cwd ${cwd}`);
}

function assertReadSandbox(thread) {
  const refuse = (why) => fail(EXIT.TRANSPORT,
    `the read sandbox is not what was asked for (${why}); refusing to continue rather than run under an unknown sandbox`);
  const applied = thread.activePermissionProfile?.id ?? null;
  if (applied !== READ_PROFILE) refuse(`server reports profile ${JSON.stringify(applied)}`);
  const sb = thread.sandbox ?? null;
  if (sb?.type !== "workspaceWrite") refuse(`sandbox type is ${JSON.stringify(sb?.type ?? null)}, so the $TMPDIR grant did not apply`);
  // Egress is the level's headline promise — `--level read --network` is a hard usage error precisely
  // because read never grants it. A `network` table in the user's own permissions profile turns it back
  // on, and the server says so right here in the object this guard already holds.
  if (sb.networkAccess === true) refuse("the sandbox has network access, which --level read never grants");
  // TMPDIR unset is a real degraded state, not a formatting quirk: the server then grants nothing and
  // read-level tests cannot run. Test the variable separately from resolving it — path.resolve("") is the
  // process's own cwd, so folding the two together produced a refusal that named the caller's repository
  // as the expected writable root.
  const tmp = process.env.TMPDIR;
  if (!tmp) refuse("TMPDIR is unset, so the server grants no temp directory at all; export TMPDIR and retry");
  const want = canonPath(tmp);
  if (!want) refuse(`TMPDIR is set to ${JSON.stringify(tmp)}, which does not resolve to a real directory`);
  const got = (sb.writableRoots ?? []).map(canonPath);
  // Exactly one root, and it is TMPDIR — unless the cwd IS the tmpdir, in which case the server subtracts
  // it from writableRoots and reports it under runtimeWorkspaceRoots, exactly as at write level. Demanding
  // it in both places refused `--level read --cwd $TMPDIR`, which is a legitimate scratch-dir invocation.
  // The cwd is checked at BOTH levels. At write level it decides where the turn writes; at read level it
  // decides which tree the turn READS, and a server that put us somewhere else would have the run answer
  // confidently about the wrong repository. Nothing in the sandbox object reveals it.
  const workspace = (thread.runtimeWorkspaceRoots ?? []).map(canonPath);
  if (!workspace.includes(canonPath(cwd)))
    refuse(`the workspace roots are ${JSON.stringify(thread.runtimeWorkspaceRoots ?? [])}, which do not include --cwd ${cwd}`);
  const cwdIsTmp = canonPath(cwd) === want;
  // When --cwd IS the tmpdir the server subtracts it from writableRoots and reports it in the workspace
  // roots instead — already verified just above — so an empty root list is correct there, not a dropped
  // grant.
  const ok = cwdIsTmp ? got.length === 0 : (got.length === 1 && got[0] === want);
  if (!ok)
    refuse(`writable roots are ${JSON.stringify(sb.writableRoots ?? [])}, expected exactly [${JSON.stringify(want)}]`);
}

// Assigned by setup(), which runs inside main()'s try — a Bail thrown at module top level would be an
// uncaught exception and would print a stack trace instead of the intended usage error.
let opts, cwd, sandbox, spawnArgs;
let codexHome = null;   // null means the caller's own ~/.codex, which --host-home asks for
let roots = [];

function setup() {
  opts = parseArgs(process.argv.slice(2));

  // Two levels, mirroring Claude's own subagents: a reader that can run things but not touch your files,
  // and a writer confined to a directory you chose. Everything else is a modifier.
  //
  // read  : the ":read-only" permission profile, extended to make $TMPDIR writable. Your files, the repo
  //         and /tmp all stay unwritable; the temp dir is what tools need to start at all. Without it a
  //         reader cannot run the test suite, which Claude's own read-only subagent can — that gap is the
  //         whole reason the profile is here rather than a plain sandbox: "read-only".
  // write : workspace-write with cwd as the writable root, plus --commit / --writable / --network.
  sandbox = opts.level === "read" ? null : "workspace-write";

  if (opts.level === "read" && (opts.network || opts.writable.length))
    fail(EXIT.USAGE, "--network and --writable belong to --level write");

  // --cwd is the primary writable root above read, so it needs the same guard as a hand-added root.
  cwd = resolveDir(opts.cwd, "--cwd");
  if (opts.level !== "read") checkRoot(cwd);

  if (opts.level !== "read") acquireLock(cwd);

  // Deduped, because the SERVER dedupes what it is given: sending /x twice (or /x and /x/, which
  // resolveDir collapses) made assertWriteSandbox compare two entries against the server's one and fail
  // the run with exit 4 — a permanent flag redundancy reported as "codex crashed".
  // Deduped AND with the cwd subtracted, because the server does BOTH and I had modelled only the first:
  // it drops the workspace root from writableRoots (workspaceWrite implies it, and it is reported under
  // runtimeWorkspaceRoots instead). Sending it anyway made assertWriteSandbox compare [cwd] against [] and
  // refuse a legitimate `--cwd X --writable X` with exit 4 — "codex crashed" for a redundant flag.
  roots = [...new Set(opts.writable.map((d) => checkRoot(resolveDir(d, "--writable"))))]
    .filter((r) => r !== cwd);
  if (opts.commit) {
    // The COMMON dir, not the per-worktree one. A narrower whitelist was measured and rejected: granting
    // {worktrees/<name>, objects, refs, logs/refs} does let add+commit through for a LINKED worktree on the
    // `files` ref backend, but `git branch -D` and `git tag -d` fail (packed-refs.lock is at the .git
    // root), `git gc` fails, every commit prints a packed-refs.lock error, and a reftable repo or a MAIN
    // worktree — where index.lock and COMMIT_EDITMSG live at the root — cannot be narrowed at all.
    // workspace-write has no deny-list, so "grant .git except hooks and config" is unexpressible here;
    // expressing it needs a permissions profile, which is a larger change than this flag.
    const r = spawnSync("git", ["-C", cwd, "rev-parse", "--path-format=absolute", "--git-common-dir"], { encoding: "utf8" });
    if (r.status !== 0) fail(EXIT.USAGE, "--commit needs a git repository at --cwd");
    const resolved = checkRoot(resolveDir(r.stdout.trim(), "the repository git directory"));
    // From a linked worktree the common dir is the MAIN clone's .git — config, hooks and every ref.
    // Granting it is sometimes necessary but never incidental, so say so out loud.
    process.stderr.write(`codex-delegate: --commit grants write access to ${resolved} (config, hooks, all refs)\n`);
    if (resolved !== cwd && !roots.includes(resolved)) roots.push(resolved);
  }

  const config = [
    ["web_search", "disabled"],
    // A reader that cannot write $TMPDIR cannot start vitest at all (it mkdirs there before running).
    // Extending ":read-only" opens exactly that and nothing else — /tmp stays excluded.
    ...(opts.level === "read" ? [
      [`permissions.${READ_PROFILE}.extends`, '":read-only"'],
      [`permissions.${READ_PROFILE}.filesystem`, '{":tmpdir"="write"}'],
      ["default_permissions", `"${READ_PROFILE}"`]
    ] : []),
    // Omitted entirely when the caller did not name one, so ~/.codex/config.toml decides.
    ...(opts.effort ? [["model_reasoning_effort", opts.effort]] : []),
    // Sent UNCONDITIONALLY at write level, unlike --effort three lines up, and the difference is the
    // point: effort is a preference the caller may delegate to their config, whereas the sandbox is what
    // assertWriteSandbox then demands the server report back. Sending these only when a flag was given
    // left the flagless case to config.toml — so any `[sandbox_workspace_write]` in a user's config made
    // every write run fail that assert with exit 4, which reads as "codex crashed". The sandbox is a
    // function of the flags alone; that is what makes asserting it meaningful.
    ...(opts.level === "write" ? [
      ["sandbox_workspace_write.network_access", String(Boolean(opts.network))],
      ["sandbox_workspace_write.writable_roots", `[${roots.map((r) => JSON.stringify(r)).join(",")}]`]
    ] : [])
  ];
  spawnArgs = ["--strict-config", ...config.flatMap(([k, v]) => ["-c", `${k}=${v}`]), "app-server"];
  codexHome = opts.hostHome ? null : isolatedHome();
}

// ---------------------------------------------------------------- transport

let child, closed = false, settled = false, flushing = false;
const pending = new Map();
let stderrBuf = "";
let stderrDropped = 0;
const STDERR_KEEP = 64 * 1024;
// A line the client cannot parse is a protocol fact, not noise. Failing the run on one is wrong — codex
// may print a banner one day — but discarding it silently means a malformed stream looks like a quiet one.
let unparsedLines = 0;

function shutdown() {
  if (closed || !child) { releaseLock(); return; }
  closed = true;
  try { child.stdin.end(); } catch {}
  // detached:true gave the child its own process group, so the negative pid reaches its descendants
  // too — killing only the app-server pid leaves orphaned test servers behind.
  const killGroup = (sig) => { try { process.kill(-child.pid, sig); } catch { try { child.kill(sig); } catch {} } };
  killGroup("SIGTERM");
  // The lock covers this process's lifetime only, NOT the group's: the timer is unref'd and
  // process.on("exit", releaseLock) frees the lock as soon as we exit, which is normally before SIGKILL
  // lands. So a next writer can enter the directory while our descendants — test servers, browsers — are
  // still dying in it. Serialising that properly means awaiting the group with a deadline; until then,
  // do not read this lock as a guarantee that the directory is quiet.
  setTimeout(() => { killGroup("SIGKILL"); releaseLock(); }, 2000).unref?.();
}

function abort(code, msg) {
  if (settled) return;
  settled = true;
  process.stderr.write(`codex-delegate: ${msg}\n`);
  if (stderrBuf.trim()) {
    if (stderrDropped) process.stderr.write(`[${stderrDropped} earlier bytes of stderr dropped]\n`);
    process.stderr.write(`${stderrBuf.trim()}\n`);
  }
  process.exitCode = code;
  // The deadline can fire while still reading the prompt from stdin, before any child exists. Without
  // this the process announces its own timeout and then blocks on stdin forever.
  if (!child) { try { process.stdin.destroy(); } catch {} }
  shutdown();
}

function rejectAllPending(err) {
  for (const p of pending.values()) p.reject(err);
  pending.clear();
}

// ---------------------------------------------------------------- state

let rootThreadId = null, rootTurnId = null;
const commands = [];        // root-thread commandExecution items only
const messages = [];        // root-thread agentMessage items only
const fileChanges = [];     // root-thread fileChange items: what the turn actually wrote
const escalations = [];     // refused permission requests — the sandbox was sized too small
const interactions = [];    // requests that needed a human: no sandbox change can answer them
let turnStatus = null;
let turnError = null;
let selectedModel = null;   // what the server resolved, which may not be what was asked for
let selectedEffort = null;  // likewise: with no --effort this is whatever config.toml chose
let effectiveSandbox = null;   // the sandbox the SERVER applied, not the one we asked for
let verifyResult = null;    // the caller-run check, the one piece of evidence the model cannot author

// Fail CLOSED on BOTH ids. Thread alone is not enough: a stale item from an earlier turn on the same
// thread, or a completion delivered before the turn/start response, would otherwise be accepted as ours.
// Notifications carry turnId as a required field; use it.
// The turn id does not live in the same place for every message: ItemCompletedNotification carries a
// required top-level `turnId`, while TurnCompletedNotification carries only `threadId` and `turn`.
// Reading `turnId` for both silently rejects every real completion.
const turnIdOf = (p) => p?.turnId ?? p?.turn?.id ?? null;
const isRoot = (p) =>
  rootThreadId !== null && (p?.threadId ?? null) === rootThreadId &&
  rootTurnId !== null && turnIdOf(p) === rootTurnId;

// Events can share a stdout chunk with the turn/start response and so arrive before rootTurnId is known.
// Holding them keyed by their own turnId lets the right ones be replayed once the id is established,
// instead of being either dropped or waved through.
const early = [];
function replayEarly() {
  const held = early.splice(0, early.length);
  // Completion last, whatever order it arrived in: replaying it first would call finish() before the
  // items it summarises had been counted, and the turn would report as empty.
  const terminal = (m) => m.method === "turn/completed";
  for (const m of held.filter((m) => !terminal(m))) handleMessage(m);
  for (const m of held.filter(terminal)) handleMessage(m);
}

function handleServerRequest(msg) {
  const send = (result) => child.stdin.write(`${JSON.stringify({ jsonrpc: "2.0", id: msg.id, result })}\n`);
  const sendError = (message) => child.stdin.write(
    `${JSON.stringify({ jsonrpc: "2.0", id: msg.id, error: { code: -32601, message } })}\n`
  );
  // Attribution for REQUESTS must fail closed, and cannot demand ids the schema does not always carry:
  // MCP elicitation has a nullable turnId, and attestation and token refresh carry no ids at all. So a
  // request counts as ours unless it positively proves it belongs to another thread.
  // The legacy applyPatch/execCommand pair identifies its conversation with `conversationId`, not
  // `threadId`; checking only the latter attributed another thread's refusal to us.
  const owner = msg.params?.threadId ?? msg.params?.conversationId ?? null;
  const foreign = rootThreadId !== null && owner != null && owner !== rootThreadId;

  // Refusal shapes differ per method; they are taken from the pinned schema-<version>/*ApprovalResponse.json.
  // `decline` is only valid for the two item/* approvals — the legacy pair accepts abort|allow|approved,
  // and the permissions request answers with a granted profile rather than a decision at all.
  const REFUSALS = {
    "item/commandExecution/requestApproval": { decision: "decline" },
    "item/fileChange/requestApproval": { decision: "decline" },
    "applyPatchApproval": { decision: "abort" },
    "execCommandApproval": { decision: "abort" },
    "item/permissions/requestApproval": { permissions: { fileSystem: null, network: null } },
  };
  // An MCP form is a request for a human, not for a wider sandbox — declining it is valid, but
  // classifying it as "the sandbox was too small" would send the caller to fix the wrong thing.
  if (msg.method === "mcpServer/elicitation/request") {
    if (!foreign) interactions.push(msg.method);
    send({ action: "decline" });
    return;
  }

  const refusal = REFUSALS[msg.method];
  if (refusal) {
    // Granting here would let Codex step outside the sandbox the caller chose — that is the caller's
    // call, not this driver's. Always refuse; count it against OUR sandbox unless the request proves it
    // belongs to another thread, so a request carrying no ids at all still fails closed.
    // Recorded whichever thread asked. The root-only filter elsewhere exists so a CHILD's command cannot
    // satisfy the gate — that is evidence of success, and evidence of success must be strict. An
    // escalation is evidence of FAILURE, and that must be inclusive: the refusal below is sent
    // unconditionally, so a subagent really was blocked, and reporting a clean run would hide it.
    const detail = String(msg.params?.command ?? msg.params?.reason ?? msg.params?.message ?? "").slice(0, 200);
    escalations.push({ method: msg.method, detail, thread: owner, subagent: foreign });
    send(refusal);
    return;
  }

  // Attestation, ChatGPT token refresh, and anything a later version adds. These are not escalations
  // and must not be reported as one; an approval-shaped result would be invalid, so answer with an
  // honest JSON-RPC error.
  if (!foreign) interactions.push(msg.method);
  sendError(`${msg.method} is not supported by codex-delegate`);
}

function handleMessage(msg) {
  if (msg.id !== undefined && !msg.method) {
    const p = pending.get(msg.id);
    if (!p) return;
    pending.delete(msg.id);
    // Assign the root ids HERE, synchronously, not in the await continuation. readline dispatches every
    // line of one stdout chunk in a single synchronous burst, so notifications sharing a chunk with this
    // response would otherwise be handled while the id is still null — and the filters would let a
    // foreign thread's events through.
    if (msg.result && (p.method === "thread/start" || p.method === "thread/resume")) {
      rootThreadId = msg.result.thread?.id ?? null;
      selectedModel = msg.result.model ?? null;
      selectedEffort = msg.result.reasoningEffort ?? null;
    }
    if (msg.result && p.method === "turn/start") {
      rootTurnId = msg.result.turn?.id ?? null;
      replayEarly();          // anything that shared this chunk can now be attributed
    }
    if (msg.error) {
      // -32601 means the server does not know a method this driver sends, which after a codex upgrade is
      // the single most likely failure — and as a raw JSON blob under a generic transport error it reads
      // as a crash rather than as protocol drift. Name it and say what to do.
      const e = new Error(msg.error.code === -32601
        ? `the server does not support ${p.method} (JSON-RPC -32601). The pinned schema-<version>/ is ` +
          `probably behind \`codex --version\`: regenerate it and re-run the eval suites.`
        : `${p.method}: ${JSON.stringify(msg.error)}`);
      e.rpcCode = msg.error.code;
      p.reject(e);
    } else p.resolve(msg.result);
    return;
  }
  if (msg.id !== undefined && msg.method) return handleServerRequest(msg);

  const p = msg.params;

  // Turn-scoped notifications that arrive before the turn id is known are held, not judged.
  const turnScoped = msg.method === "item/completed" || msg.method === "turn/completed";
  if (turnScoped && rootTurnId === null) { early.push(msg); return; }

  if (msg.method === "item/completed" && isRoot(p)) {
    const it = p.item;
    if (it?.type === "commandExecution") commands.push({ command: String(it.command), exitCode: it.exitCode, status: it.status });
    if (it?.type === "agentMessage" && it.text) messages.push({ text: it.text, phase: it.phase ?? null });
    // A write-level run said nothing about what it WROTE. The schema carries it — FileChangeThreadItem
    // requires {changes:[{path,kind,diff}], status}, and PatchApplyStatus includes failed and declined —
    // so a patch that failed for a reason other than a refused approval was invisible in both the report
    // and the exit code. Same hole the command list already closed.
    if (it?.type === "fileChange") {
      for (const ch of it.changes ?? [])
        // PatchChangeKind is a oneOf of OBJECTS ({type:"add"} / {type:"delete"} / {type:"update",move_path}),
        // not a string. Storing it raw rendered every write run's blast-radius line as "[object Object]",
        // and the fixture had invented the string form — the third time a made-up shape in that file made
        // the suite green against something the server never sends.
        // move_path is the destination of a rename, and dropping it made the report state a falsehood
        // silently: filesTouched named the path that no longer exists and omitted the one that does, so a
        // coordinator harvesting the change set read a deleted file and never learned of the new one.
        fileChanges.push({ path: String(ch.path), kind: ch.kind?.type ?? String(ch.kind),
                           move: ch.kind?.move_path ?? null, status: it.status });
    }
  }
  // A subagent finishing its own turn, or an earlier turn on our own thread, must not end ours.
  if (msg.method === "turn/completed" && isRoot(p)) {
    turnStatus = p?.turn?.status ?? "unknown";
    // Populated only when the turn failed, and it carries an enumerated cause worth acting on:
    // usageLimitExceeded / serverOverloaded -> back off and retry the same turn, do not re-prompt;
    // contextWindowExceeded -> the handoff was too large, split it; unauthorized -> stop;
    // sandboxError -> the rights level was wrong; responseStreamDisconnected -> transport, retry.
    turnError = p?.turn?.error ?? null;
    finish();
  }
}

// `reason` is set when the run is being cut short (a timeout) rather than ending on its own. Everything
// streamed so far is still in memory, and a run that did four useful greps before the clock ran out
// should hand those back rather than throw them away.
// codexErrorInfo is either a bare string or a one-key tagged object; reading .type gives "unknown".
function errKind(e) {
  const i = e?.codexErrorInfo ?? e?.type;
  if (typeof i === "string") return i;
  if (i && typeof i === "object") return Object.keys(i)[0] ?? "unknown";
  return "unknown";
}

function finish(reason) {
  if (settled) return;
  settled = true;
  if (reason) turnStatus = reason;

  // A command that merely produced a number is not evidence: `false` exits 1 and would have passed.
  // Require a command that actually succeeded.
  const ran = commands.filter((c) => c.status === "completed" && c.exitCode === 0);
  // The schema's CommandExecutionStatus is {inProgress, completed, failed, declined} and exitCode may be
  // null, so a command can FAIL while carrying no numeric code at all. Keying the failure set on the code
  // alone put those in `blocked`, which the footer prints but the exit ladder ignores — the report said
  // "NEVER RAN pnpm test" while the run exited 0 under an answer claiming the tests passed.
  const verdictFailed = (c) => c.status === "failed" || c.status === "declined";
  const blocked = commands.filter((c) => !verdictFailed(c) && typeof c.exitCode !== "number");
  // A command that ran and FAILED belongs to neither set, so it was printed nowhere — while the footer
  // told the reader to check the list. A suite that ran and failed under a final answer claiming it
  // passed is exactly the case this report exists to expose.
  const failedCmds = commands.filter((c) => verdictFailed(c) || (typeof c.exitCode === "number" && c.exitCode !== 0));
  // A patch that could not be applied is the same class of fact as a command that failed, and was counted
  // nowhere: PatchApplyStatus has failed and declined, and neither reached the ladder.
  const failedPatches = fileChanges.filter(verdictFailed);
  // Events can only show that SOMETHING succeeded, never that the right thing did — Codex opens most
  // turns by reading its own skill files, and that alone satisfies any generic gate. --expect-command
  // is the caller declaring what the evidence must look like.
  const expected = opts.expectRe ? ran.filter((c) => opts.expectRe.test(c.command)) : ran;
  // Only a final_answer counts. Falling back to the last message of any phase turns the model's
  // thinking-out-loud into the deliverable, and the run reports success on commentary.
  // The schema permits phase: null, and older servers omit it. Prefer an explicit final_answer; fall back
  // to the last non-blank unphased message only when nothing was phased at all.
  const nonBlank = messages.filter((m) => String(m.text).trim());
  const phased = nonBlank.filter((m) => m.phase === "final_answer");
  const final = phased.at(-1) ?? (nonBlank.every((m) => m.phase == null) ? nonBlank.at(-1) ?? null : null);
  const answer = final?.text ?? "";
  const commentaryOnly = !final && messages.length > 0;

  // --verify runs on its OWN schedule, not as a reward for having passed the weaker gates. It used to be
  // gated on the ladder already reading 0, which inverted the evidence: --expect-command greps command
  // strings the MODEL wrote and is defeated by `true # vitest`, while --verify is a command the CALLER
  // runs afterwards and cannot be authored by the model. The weak check was cancelling the strong one, and
  // the report said `verify: null` — so a proven-broken end state and a proven-good one printed alike.
  //
  // Skipped on a timeout only, and for a reason: the deadline fires while Codex is still alive and
  // possibly mid-write, so the check would read a torn tree. verifySkipped records which it was, because
  // "not measured" and "not requested" are different facts about the run.
  let verifySkipped = opts.verify ? null : "not-requested";
  if (opts.verify) {
    if (turnStatus === "timedOut") verifySkipped = "turn-timed-out";
    else if (turnStatus !== "completed") verifySkipped = `turn-${turnStatus}`;
    else {
      // The budget is the caller's, not a private 300s: a --timeout 5 run must not spend 300s in here.
      // killSignal matters as much as the timeout — spawnSync's default SIGTERM is ignorable, so a
      // verifier that traps it ran to completion and was still reported as timed out.
      // maxBuffer: the default 1MB kills a verifier that prints a lot and reports status null / ENOBUFS,
      // turning a passing check into a failure.
      const budgetMs = Math.max(1000, Math.min(300000, opts.timeout * 1000 - (Date.now() - startedAtMs)));
      const v = spawnSync("/bin/sh", ["-c", opts.verify],
        { cwd, encoding: "utf8", timeout: budgetMs, killSignal: "SIGKILL", maxBuffer: 64 * 1024 * 1024 });
      // "Exited non-zero" and "could not be run at all" are different facts and must not render alike:
      // one means the work is missing, the other means the verifier is broken, and they call for opposite
      // responses. The classification is on the OBSERVED EXIT STATUS, not on whether spawnSync also
      // reported an error:
      //   127 / 126  the shell never ran the command — a typo, or a tool missing from the DRIVER's PATH
      //              (a launchd or hook context routinely lacks pnpm). Says nothing about the work.
      //   no status  never observed an exit at all: killed at the deadline, or spawn itself failed.
      //   status 0   the command DID exit successfully. spawnSync's timeout waits on the stdout pipe as
      //              well as the process, so a verifier that passes while a background process holds the
      //              pipe returns status 0 WITH error ETIMEDOUT — that is a pass we are holding proof of,
      //              and reporting it as unmeasurable throws the proof away.
      const noStatus = v.status === null || v.status === undefined;
      const notRunnable = v.status === 127 || v.status === 126;
      const measured = !noStatus && !notRunnable;
      verifyResult = {
        command: opts.verify, exitCode: v.status, signal: v.signal ?? null,
        ok: measured && v.status === 0, measured,
        error: v.error ? String(v.error.code ?? v.error.message) : null,
        stdout: String(v.stdout ?? "").slice(-2000), stderr: String(v.stderr ?? "").slice(-2000)
      };
    }
  }
  const verifyPassed = verifyResult?.ok === true;
  const verifyFailed = verifyResult != null && !verifyPassed;

  // A refused escalation means the task hit the edge of the sandbox it was given, so the work is very
  // likely incomplete — detectable without reading the prose.
  let code = EXIT.OK;
  if (turnStatus === "timedOut") code = EXIT.TIMEOUT;
  else if (turnStatus !== "completed") code = EXIT.TURN_NOT_COMPLETED;
  // An unattended interaction the driver could not answer means the turn proceeded without something it
  // asked for. That is never a success, and it is not an escalation either — no sandbox change fixes it.
  else if (interactions.length) code = EXIT.INTERACTION;
  // Escalations before NO_COMMANDS: a refused approval explains the missing command, and reporting
  // "nothing ran" would hide the reason.
  else if (escalations.length) code = EXIT.ESCALATED;
  // Above the proxies below it: this one measured the end state directly instead of inferring it.
  // "The check said no" and "the check could not be run" are different instructions to the caller — redo
  // the work, versus fix the verifier — so they get different codes. Reporting the second as 9 told the
  // caller to discard work the run never measured, while the text beside it said the opposite.
  else if (verifyResult && !verifyResult.measured) code = EXIT.VERIFY_UNMEASURABLE;
  else if (verifyFailed) code = EXIT.VERIFY_FAILED;
  // --allow-no-commands waives the "at least one command" floor. It must NOT waive an expectation the
  // caller declared: asking for proof and then accepting its absence is the exact failure this gate exists
  // to prevent. A passing --verify does not waive it either — the end state can be right while the work
  // drifted, e.g. a stale dist/ satisfying `test -f dist/index.js` for a build that never ran.
  else if (expected.length === 0 && (opts.expectRe || !opts.allowNoCommands)) code = EXIT.NO_COMMANDS;
  else if (!answer) code = EXIT.NO_ANSWER;
  // A command that ran and failed is a failure of the work, whatever the answer claims — one incidental
  // success (a skill-file read) must not mask it. A PASSING --verify overrules it, because iterative work
  // normally contains failed commands: the first test run fails, the model fixes it, the second passes.
  // The waiver is on the check's RESULT; keying it on the flag's presence let a check that never executed
  // wave a real failure through.
  else if ((failedCmds.length || failedPatches.length) && !verifyPassed) code = EXIT.COMMAND_FAILED;

  const report = {
    ok: code === EXIT.OK, exitCode: code, level: opts.level, sandbox: effectiveSandbox, cwd,
    writableRoots: roots, network: Boolean(opts.network),
    // Which Codex installation answered. Two runs that differ only in this can differ in everything else,
    // so a report that omits it cannot be compared with another.
    codexHome,
    // What was REQUESTED; null means the thread inherited config.toml. reasoningEffort below is what the
    // server actually selected, which is the one worth reading back.
    effort: opts.effort ?? null, reasoningEffort: selectedEffort,
    model: selectedModel, turnStatus, turnError, threadId: rootThreadId,
    commandsRun: ran.length, commandsMatchingExpectation: expected.length,
    commandsFailed: failedCmds.length, commandsBlocked: blocked.length,
    // For a rename the file that EXISTS afterwards is the destination; report that, not the source.
    filesTouched: fileChanges.filter((f) => f.status === "completed").map((f) => f.move ?? f.path),
    fileChangesFailed: failedPatches,
    escalations, interactions, unparsedLines, expectCommand: opts.expect ?? null,
    // null only when no --expect-command was given, so a caller can tell "not asked" from "asked and missed".
    expectationOk: opts.expectRe ? expected.length > 0 : null,
    verify: verifyResult, verifySkipped,
    answerPhase: final?.phase ?? null, commentaryOnly, answer
  };

  let out;
  if (opts.json) {
    out = `${JSON.stringify({ ...report, commands }, null, 2)}\n`;
  } else {
    const L = [answer, ""];
    L.push(`--- verification -----------------------------------------`);
    L.push(`level=${opts.level} sandbox=${effectiveSandbox?.type ?? sandbox} turn=${turnStatus} answerPhase=${final?.phase ?? "none"}`);
    // Only the surprising case is worth a line: on the host home the caller's plugins and skills were in
    // the turn, so this run is not comparable with an isolated one.
    if (codexHome === null) L.push("home=host — the caller's plugins and skills were loaded into this turn");
    if (!opts.ephemeral) L.push(`threadId=${rootThreadId}  (continue with --resume ${rootThreadId})`);
    L.push(`commands: ${ran.length} succeeded` +
      `${failedCmds.length ? `, ${failedCmds.length} FAILED` : ""}` +
      `${blocked.length ? `, ${blocked.length} never ran` : ""}`);
    for (const c of ran.slice(-8)) L.push(`  exit=${c.exitCode} ${c.command.slice(0, 90)}`);
    for (const c of failedCmds) L.push(`  FAILED exit=${c.exitCode} ${c.command.slice(0, 90)}`);
    for (const c of blocked) L.push(`  NEVER RAN  ${c.command.slice(0, 90)}`);
    const wrote = fileChanges.filter((f) => f.status === "completed");
    if (wrote.length) {
      L.push(`files: ${wrote.length} written`);
      for (const f of wrote.slice(-12)) L.push(f.move ? `  rename ${f.path} -> ${f.move}` : `  ${f.kind} ${f.path}`);
    }
    for (const f of failedPatches) L.push(`  PATCH ${String(f.status).toUpperCase()} ${f.path}`);
    if (escalations.length) {
      L.push(`escalations refused: ${escalations.length} — the sandbox was too small for this task.`);
      for (const e of escalations) L.push(`  ${e.method} ${e.detail}`);
      L.push(`  widen it with --writable <dir> or --network rather than approving per command.`);
    }
    // Both checks always report their verdict. Printing only the exit code made a run whose end state was
    // proven good and one whose end state was proven broken produce byte-identical reports.
    if (verifyResult) {
      // "could not be measured" is not "the work is not there" — a verifier that overran maxBuffer or the
      // deadline says nothing about the work, and printing it as FAIL makes the caller discard good work.
      L.push(verifyResult.measured
        ? `verify: \`${verifyResult.command}\` -> ${verifyResult.ok ? "PASS" : "FAIL"} (exit ${verifyResult.exitCode})` +
          (verifyResult.error ? ` [${verifyResult.error} while draining, exit status observed anyway]` : "")
        : `verify: \`${verifyResult.command}\` COULD NOT BE MEASURED (` +
          (verifyResult.exitCode === 127 ? "command not found on the driver's PATH"
            : verifyResult.exitCode === 126 ? "found but not executable"
            : verifyResult.error ?? "no exit status") +
          `${verifyResult.signal ? `, killed by ${verifyResult.signal}` : ""}) — this says nothing about the work; fix the verifier.`);
    } else if (opts.verify) {
      L.push(`verify: \`${opts.verify}\` NOT RUN (${verifySkipped}) — the end state is unmeasured.`);
    }
    if (opts.expectRe) {
      L.push(expected.length
        ? `expect-command /${opts.expect}/: ${expected.length} successful command(s) matched`
        : `expect-command /${opts.expect}/: NO successful command matched — the turn may have drifted`);
    }
    if (unparsedLines) L.push(`${unparsedLines} unparsable line(s) from the server — the pinned schema may be behind \`codex --version\`.`);
    if (interactions.length) L.push(`UNANSWERABLE server requests — no sandbox change fixes these: ${interactions.join(", ")}`);
    if (turnStatus !== "completed") {
      L.push(`TURN ${String(turnStatus).toUpperCase()} — the answer above is incomplete.`);
      if (turnError) L.push(`  cause: ${errKind(turnError)} — ${turnError.message ?? ""}`);
      if (stderrBuf.trim()) L.push(`  stderr: ${stderrBuf.trim().split("\n").slice(-3).join(" | ")}` +
        (stderrDropped ? `  [+${stderrDropped} earlier bytes dropped]` : ""));
    }
    else if (ran.length === 0) L.push(`NOT TRUSTWORTHY: no command executed; the answer is unverified.`);
    L.push(`Note: a passing gate proves commands ran, not that the right ones did. Check the list.`);
    out = `${L.join("\n")}\n`;
  }
  process.exitCode = code;
  // Exit only once stdout has actually drained. A large report on a pipe is chunked, and exiting on the
  // next tick truncates it at the pipe buffer — measured at 262144 bytes for a 20MB report.
  flushing = true;
  process.stdout.write(out, () => { flushing = false; shutdown(); process.exit(code); });
  // If stdout never drains, the report did not reach the caller — that is a transport failure, not
  // the success the run would otherwise have been.
  setTimeout(() => {
    process.stderr.write("codex-delegate: stdout did not drain; report may be truncated\n");
    shutdown(); process.exit(EXIT.TRANSPORT);
  }, 5000).unref?.();
}

// ---------------------------------------------------------------- run

async function main() {
  setup();
  // Once a child exists, a timeout hands back the partial result rather than discarding it; before that
  // there is nothing to report, so abort() also has to unblock a stdin read that may never end.
  const deadline = setTimeout(() => {
    if (child && rootThreadId) finish("timedOut");
    else abort(EXIT.TIMEOUT, `timed out after ${opts.timeout}s`);
  }, opts.timeout * 1000);
  deadline.unref?.();

  let prompt = opts.prompt;
  if (prompt === undefined) {
    if (process.stdin.isTTY) fail(EXIT.USAGE, "no prompt: pass --prompt or pipe one on stdin");
    process.stdin.setEncoding("utf8");   // raw Buffers split multi-byte chars at chunk boundaries
    let s = "";
    for await (const c of process.stdin) {
      s += c;
      if (Buffer.byteLength(s) > MAX_PROMPT_BYTES) fail(EXIT.USAGE, `prompt exceeds ${MAX_PROMPT_BYTES} bytes`);
    }
    prompt = s;
  }
  if (settled) throw new Bail();   // aborted while reading stdin; the exit code is already set
  prompt = prompt.trim();
  if (!prompt) fail(EXIT.USAGE, "empty prompt");

  child = spawn("codex", spawnArgs, {
    cwd, stdio: ["pipe", "pipe", "pipe"], detached: true,
    env: codexHome === null ? process.env : { ...process.env, CODEX_HOME: codexHome },
  });
  child.stderr.setEncoding("utf8");
  // Bounded: a run may legitimately last two hours, and abort() prints this whole buffer. Keep the TAIL,
  // because the last words before a crash are the useful ones, and say how much was dropped.
  child.stderr.on("data", (c) => {
    stderrBuf += c;
    if (stderrBuf.length > STDERR_KEEP) {
      stderrDropped += stderrBuf.length - STDERR_KEEP;
      stderrBuf = stderrBuf.slice(-STDERR_KEEP);
    }
  });
  child.on("error", (e) => { rejectAllPending(e); abort(EXIT.TRANSPORT, `cannot start codex: ${e.message}`); });
  child.on("exit", (code, signal) => {
    const e = new Error(`codex app-server exited (${signal ? `signal ${signal}` : `code ${code}`})`);
    rejectAllPending(e);
    if (!settled) abort(EXIT.TRANSPORT, e.message);
  });
  child.stdin.on("error", () => {});

  readline.createInterface({ input: child.stdout }).on("line", (line) => {
    let msg;
    try { msg = JSON.parse(line); } catch { unparsedLines++; return; }   // readline already reassembles split lines
    try { handleMessage(msg); } catch (e) { abort(EXIT.TRANSPORT, `protocol handling failed: ${e.message}`); }
  });

  let nextId = 1;
  const request = (method, params) => {
    const id = nextId++;
    child.stdin.write(`${JSON.stringify({ jsonrpc: "2.0", id, method, params })}\n`);
    return new Promise((resolve, reject) => pending.set(id, { resolve, reject, method }));
  };

  await request("initialize", {
    clientInfo: { title: "codex-delegate", name: "Claude Code", version: "2.0" },
    capabilities: {
      experimentalApi: false, requestAttestation: false,
      // Every one of these is parsed and dropped: the driver reads item/completed and turn/completed and
      // nothing else. Left empty, a `pnpm test` streams its whole output through the pipe line by line for
      // no reader. The list is taken from ServerNotification in the pinned schema rather than guessed —
      // the command-output streams are the large ones, and are exactly what a test-running delegation
      // produces most of.
      optOutNotificationMethods: [
        "item/agentMessage/delta",
        "item/reasoning/summaryTextDelta", "item/reasoning/summaryPartAdded", "item/reasoning/textDelta",
        "item/commandExecution/outputDelta", "command/exec/outputDelta", "process/outputDelta",
        "item/fileChange/outputDelta", "item/plan/delta"
      ]
    }
  });
  child.stdin.write(`${JSON.stringify({ jsonrpc: "2.0", method: "initialized", params: {} })}\n`);

  // Standing rules belong on the thread, not in the task prompt: they then govern every turn of a
  // resumed thread and do not compete with the task text for attention. `codex exec` cannot do this.
  const developerInstructions = [
    "You are being driven by a Claude Code coordinator, unattended. Nobody will answer a question.",
    "Use the local shell and filesystem only. Do not use web search; cite files you actually read.",
    "If a command cannot run, reply with the single token COMMAND_BLOCKED for that step and continue.",
    "Never report a test as passing unless you ran it and saw the count in this turn.",
    "State uncertainty plainly rather than guessing; an honest 'I could not determine this' is useful."
  ].join(" ");

  // Sending `sandbox` at all suppresses the permission profile — the server reports
  // activePermissionProfile: null and the $TMPDIR grant silently disappears. So at --level read the
  // parameter is omitted and the profile is pinned via -c instead; the response is then asserted below,
  // because an unapplied profile must never pass as if it had applied.
  const sandboxParam = sandbox === null ? {} : { sandbox };
  const resuming = Boolean(opts.resume);
  // WHO may approve is as load-bearing as what the sandbox permits, and it is a separate axis. With
  // approvalsReviewer "auto_review" the server hands approvals to its own subagent, so they never reach
  // this driver: escalations stay empty, the refusal policy is silently disarmed, and a sandbox escape can
  // be granted while the run exits 0. Measured: the sandbox object is byte-identical under "user" and
  // "auto_review", so no amount of checking type/roots/network can tell them apart. `approvals_reviewer`
  // is a real config key and a menu item in the interactive TUI, so this is one toggle away by accident.
  const approvalsReviewer = "user";
  const threadReq = resuming
    ? ["thread/resume", { threadId: opts.resume, cwd, model: opts.model ?? null, approvalPolicy: "on-request", approvalsReviewer, ...sandboxParam, developerInstructions }]
    // Resumable by default. Whether a thread is worth continuing is only knowable after reading the
    // answer, and an ephemeral thread cannot be continued — so opting IN was a trap: you learned you
    // needed the flag exactly when it was too late to pass it.
    : ["thread/start", { cwd, model: opts.model ?? null, approvalPolicy: "on-request", approvalsReviewer, ...sandboxParam, developerInstructions,
        serviceName: "claude-code-codex-delegate", ephemeral: Boolean(opts.ephemeral) }];
  const thread = await request(threadReq[0], threadReq[1]);
  // Asked for above, asserted here, at BOTH levels — write level's writable-root boundary is escapable the
  // same way. The field is `required` on the response in the pinned schema, so a server that stops sending
  // it yields undefined and refuses: fail-closed by construction rather than by convention.
  // The approval POLICY is asserted for the same reason as the reviewer, and it is the reason this driver
  // uses app-server at all: where an MDM profile restricts the allowed policies, a policy it does not
  // permit is silently CLAMPED to another one, after which every command is denied while the run still
  // looks healthy. That is the failure the whole skill exists to route around — so if the server did not
  // echo the policy we asked for, stop rather than discover it one refused command at a time.
  if (thread.approvalPolicy !== "on-request")
    fail(EXIT.TRANSPORT, `the server applied approvalPolicy ${JSON.stringify(thread.approvalPolicy ?? null)}, not "on-request"; ` +
      `a clamped policy denies every command while the run still exits cleanly. Refusing to continue.`);
  if (thread.approvalsReviewer !== approvalsReviewer)
    fail(EXIT.TRANSPORT, `approvals are routed to ${JSON.stringify(thread.approvalsReviewer ?? null)}, not to this driver; ` +
      `it could approve a sandbox escape without the run ever reporting an escalation. Refusing to continue.`);
  // A resumed thread with a turn still running would hand us that turn's id from turn/start, and its
  // old events would satisfy this invocation while the new prompt was never consumed.
  effectiveSandbox = thread.sandbox ?? null;
  assertSandbox(thread);

  const st = thread.thread?.status?.type ?? null;
  if (resuming && st === "active") fail(EXIT.BUSY, `thread ${opts.resume} still has a turn running; wait for it to finish`);
  if (resuming && st && st !== "idle") fail(EXIT.TRANSPORT, `thread ${opts.resume} is ${st} and cannot be resumed`);

  await request("turn/start", {
    threadId: rootThreadId,
    input: [{ type: "text", text: prompt, text_elements: [] }],
    model: opts.model ?? null, effort: null
  });
}

// Installing a handler removes Node's default terminate-on-signal, so the handler must always end the
// process. Without the settled branch a run that has already reported ignores every signal it handles,
// and only SIGKILL reclaims it.
for (const sig of ["SIGINT", "SIGTERM"]) {
  process.on(sig, () => {
    if (settled) {
      if (flushing) return;   // the report is mid-write; let it finish or hit its own timer
      shutdown(); process.exit(process.exitCode ?? EXIT.TRANSPORT);
    }
    abort(EXIT.TRANSPORT, `interrupted by ${sig}`);
    setTimeout(() => process.exit(EXIT.TRANSPORT), 2500).unref?.();
  });
}

process.on("exit", releaseLock);

main().catch((e) => {
  if (e instanceof Bail) { shutdown(); return; }
  abort(EXIT.TRANSPORT, e.message);
});
